call_parentheses = "Always"
collapse_simple_statement = "Never"
indent_width = 4
indent_type = "Spaces"
line_endings = "Unix"
quote_style = "AutoPreferSingle"
space_after_function_names = "Never"
syntax = "LuaJIT"

[sort_requires]
enabled = true
