[bazelrc-lsp]
fetch.url = "https://github.com/salesforce-misc/bazelrc-lsp/archive/refs/tags/v$ver.tar.gz"
src.github = "salesforce-misc/bazelrc-lsp"
src.prefix = "v"

[bzl_darwin]
fetch.url = "https://get.bzl.io/darwin_amd64/$ver/bzl"
src.github = "stackb/bazel-stack-vscode"
src.prefix = "v"

[bzl_linux]
fetch.url = "https://get.bzl.io/linux_amd64/$ver/bzl"
src.github = "stackb/bazel-stack-vscode"
src.prefix = "v"

[cmake-language-server]
fetch.url = "https://github.com/regen100/cmake-language-server/archive/refs/tags/v$ver.tar.gz"
src.github = "regen100/cmake-language-server"
src.prefix = "v"

[gradle-language-server]
fetch.url = "https://github.com/microsoft/vscode-gradle/archive/refs/tags/$ver.tar.gz"
src.github = "microsoft/vscode-gradle"

[guihua-lua]
fetch.github = "ray-x/guihua.lua"
src.branch = "master"
src.git = "https://github.com/ray-x/guihua.lua"

[hlchunk-nvim]
fetch.url = "https://github.com/shellRaining/hlchunk.nvim/archive/refs/tags/v$ver.tar.gz"
src.github = "shellRaining/hlchunk.nvim"
src.prefix = "v"

[schemastore-nvim]
fetch.github = "B0o/SchemaStore.nvim"
src.branch = "main"
src.git = "https://github.com/B0o/SchemaStore.nvim"

[ts-error-translator-nvim]
fetch.url = "https://github.com/dmmulroy/ts-error-translator.nvim/archive/refs/tags/v$ver.tar.gz"
src.github = "dmmulroy/ts-error-translator.nvim"
src.prefix = "v"

[vim-jb-lua]
fetch.github = "ms0503/vim-jb.lua"
src.branch = "main"
src.git = "https://github.com/ms0503/vim-jb.lua"

[vimdoc-ja]
fetch.github = "vim-jp/vimdoc-ja"
src.branch = "master"
src.git = "https://github.com/vim-jp/vimdoc-ja"
