[bzl_darwin]
fetch.url = "https://get.bzl.io/darwin_amd64/v$ver/bzl"
src.manual = "1.5.1"

[bzl_linux]
fetch.url = "https://get.bzl.io/linux_amd64/v$ver/bzl"
src.manual = "1.5.1"

[guihua-lua]
fetch.github = "ray-x/guihua.lua"
src.branch = "master"
src.git = "https://github.com/ray-x/guihua.lua"

[schemastore-nvim]
fetch.github = "B0o/SchemaStore.nvim"
src.branch = "main"
src.git = "https://github.com/B0o/SchemaStore.nvim"

[ts-error-translator-nvim]
fetch.url = "https://github.com/dmmulroy/ts-error-translator.nvim/archive/refs/tags/v$ver.tar.gz"
src.github = "dmmulroy/ts-error-translator.nvim"
src.prefix = "v"

[vim-jb-lua]
fetch.github = "ms0503/vim-jb.lua"
src.branch = "main"
src.git = "https://github.com/ms0503/vim-jb.lua"

[vimdoc-ja]
fetch.github = "vim-jp/vimdoc-ja"
src.branch = "master"
src.git = "https://github.com/vim-jp/vimdoc-ja"
