call_parentheses = "Always"
collapse_simple_statement = "Never"
column_width = 80
indent_type = "Spaces"
indent_width = 4
line_endings = "Unix"
quote_style = "ForceSingle"
space_after_function_names = "Never"
syntax = "All"

[sort_requires]
enabled = true
