# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  awk-language-server = {
    pname = "awk-language-server";
    version = "0.10.6";
    src = fetchurl {
      url = "https://github.com/Beaglefoot/awk-language-server/archive/refs/tags/server-0.10.6.tar.gz";
      sha256 = "sha256-LbV/OGzLaeYtGVk5/TqOg5GsUKbDRPWWsN1kMa4ESFM=";
    };
  };
  css-variables-language-server = {
    pname = "css-variables-language-server";
    version = "2.8.4";
    src = fetchurl {
      url = "https://github.com/vunguyentuan/vscode-css-variables/archive/refs/tags/css-variables-language-server%402.8.4.tar.gz";
      name = "css-variables-language-server-2.8.4.tar.gz";
      sha256 = "sha256-pBubetH9LJGYmzMMTkxgrF1UVS6Ye2Rz4guQlHTjgo4=";
    };
  };
  guihua-lua = {
    pname = "guihua-lua";
    version = "d178056728548ed8a99cce94de47b7500bd6889a";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "guihua.lua";
      rev = "d178056728548ed8a99cce94de47b7500bd6889a";
      fetchSubmodules = false;
      sha256 = "sha256-GkSUwoDHFu615eTRaN2hjZJPxWe+77JqO8mEJ2YsIgw=";
    };
    date = "2026-04-10";
  };
  schemastore-nvim = {
    pname = "schemastore-nvim";
    version = "250aed7415ddd6cb3ea321490c7b35094ed9148d";
    src = fetchFromGitHub {
      owner = "B0o";
      repo = "SchemaStore.nvim";
      rev = "250aed7415ddd6cb3ea321490c7b35094ed9148d";
      fetchSubmodules = false;
      sha256 = "sha256-UQ+6s4tMJ8z+UJ41ZX1HJTiDsbkYFEUSDb+N8jVBAeY=";
    };
    date = "2026-04-17";
  };
  ts-error-translator-nvim = {
    pname = "ts-error-translator-nvim";
    version = "2.0.1";
    src = fetchurl {
      url = "https://github.com/dmmulroy/ts-error-translator.nvim/archive/refs/tags/v2.0.1.tar.gz";
      sha256 = "sha256-SSLrY2+0shDy/gvZeFmMGlLEZdtbMQT7XBS0WvF8X98=";
    };
  };
  vim-jb-lua = {
    pname = "vim-jb-lua";
    version = "c3ab5d8039e137070fc48a2e9b7931d9dedaa9fa";
    src = fetchFromGitHub {
      owner = "ms0503";
      repo = "vim-jb.lua";
      rev = "c3ab5d8039e137070fc48a2e9b7931d9dedaa9fa";
      fetchSubmodules = false;
      sha256 = "sha256-TuQgrhN/4hDn3iKF2jPWdq4KBchx1CMo8hM9tcKRMM4=";
    };
    date = "2025-02-13";
  };
  vimdoc-ja = {
    pname = "vimdoc-ja";
    version = "288ce0cf574bdd812eeb18f2070b11c1daf59106";
    src = fetchFromGitHub {
      owner = "vim-jp";
      repo = "vimdoc-ja";
      rev = "288ce0cf574bdd812eeb18f2070b11c1daf59106";
      fetchSubmodules = false;
      sha256 = "sha256-83/x+KHVKCDTZWjUhPk4ZEdJl1ab6w7Fn+evYbezgxo=";
    };
    date = "2026-04-18";
  };
}
