# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  guihua-lua = {
    pname = "guihua-lua";
    version = "4c513d5dac550af77034cced421967b393261509";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "guihua.lua";
      rev = "4c513d5dac550af77034cced421967b393261509";
      fetchSubmodules = false;
      sha256 = "sha256-e0Almh8wWGp5NxHX48Y4XGEUHtPCYOXi4BIlfeSzaIs=";
    };
    date = "2026-07-03";
  };
  schemastore-nvim = {
    pname = "schemastore-nvim";
    version = "73e89eb3e536a4dd8f991c963bd37189520c9919";
    src = fetchFromGitHub {
      owner = "B0o";
      repo = "SchemaStore.nvim";
      rev = "73e89eb3e536a4dd8f991c963bd37189520c9919";
      fetchSubmodules = false;
      sha256 = "sha256-64QPVE298/XHx+UZeuvh5GndxiLgzWn1WfLJLBeZJKQ=";
    };
    date = "2026-08-20";
  };
  ts-error-translator-nvim = {
    pname = "ts-error-translator-nvim";
    version = "2.0.1";
    src = fetchurl {
      url = "https://github.com/dmmulroy/ts-error-translator.nvim/archive/refs/tags/v2.0.1.tar.gz";
      sha256 = "sha256-SSLrY2+0shDy/gvZeFmMGlLEZdtbMQT7XBS0WvF8X98=";
    };
  };
  vim-jb-lua = {
    pname = "vim-jb-lua";
    version = "c3ab5d8039e137070fc48a2e9b7931d9dedaa9fa";
    src = fetchFromGitHub {
      owner = "ms0503";
      repo = "vim-jb.lua";
      rev = "c3ab5d8039e137070fc48a2e9b7931d9dedaa9fa";
      fetchSubmodules = false;
      sha256 = "sha256-TuQgrhN/4hDn3iKF2jPWdq4KBchx1CMo8hM9tcKRMM4=";
    };
    date = "2025-02-13";
  };
  vimdoc-ja = {
    pname = "vimdoc-ja";
    version = "d94d9114c7e6a3210e8039a7d88080f49a35bce8";
    src = fetchFromGitHub {
      owner = "vim-jp";
      repo = "vimdoc-ja";
      rev = "d94d9114c7e6a3210e8039a7d88080f49a35bce8";
      fetchSubmodules = false;
      sha256 = "sha256-WopOR07J3octH4CNpCCkIIgVl7mflyuFhngSXcgK/FQ=";
    };
    date = "2026-08-22";
  };
}
