# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  guihua-lua = {
    pname = "guihua-lua";
    version = "f8e06bd8a26dee3377d63c2adf1e57cdb58ac474";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "guihua.lua";
      rev = "f8e06bd8a26dee3377d63c2adf1e57cdb58ac474";
      fetchSubmodules = false;
      sha256 = "sha256-lupDg/yt75164H8zQs/HTKqC3Y1FnQCzoMq90nwapO8=";
    };
    date = "2026-05-27";
  };
  schemastore-nvim = {
    pname = "schemastore-nvim";
    version = "e25e63f3b24fd6b8c2fc713107ad5d5594028eac";
    src = fetchFromGitHub {
      owner = "B0o";
      repo = "SchemaStore.nvim";
      rev = "e25e63f3b24fd6b8c2fc713107ad5d5594028eac";
      fetchSubmodules = false;
      sha256 = "sha256-VhA3NUiiGs29Q23Xos/0tsWPm0Pl/CcZocznUz3/z9M=";
    };
    date = "2026-05-26";
  };
  ts-error-translator-nvim = {
    pname = "ts-error-translator-nvim";
    version = "2.0.1";
    src = fetchurl {
      url = "https://github.com/dmmulroy/ts-error-translator.nvim/archive/refs/tags/v2.0.1.tar.gz";
      sha256 = "sha256-SSLrY2+0shDy/gvZeFmMGlLEZdtbMQT7XBS0WvF8X98=";
    };
  };
  vim-jb-lua = {
    pname = "vim-jb-lua";
    version = "c3ab5d8039e137070fc48a2e9b7931d9dedaa9fa";
    src = fetchFromGitHub {
      owner = "ms0503";
      repo = "vim-jb.lua";
      rev = "c3ab5d8039e137070fc48a2e9b7931d9dedaa9fa";
      fetchSubmodules = false;
      sha256 = "sha256-TuQgrhN/4hDn3iKF2jPWdq4KBchx1CMo8hM9tcKRMM4=";
    };
    date = "2025-02-13";
  };
  vimdoc-ja = {
    pname = "vimdoc-ja";
    version = "f0ac8f17699388ab439c581be34517bde1b72df2";
    src = fetchFromGitHub {
      owner = "vim-jp";
      repo = "vimdoc-ja";
      rev = "f0ac8f17699388ab439c581be34517bde1b72df2";
      fetchSubmodules = false;
      sha256 = "sha256-Dn3Wa3eJZW6oedE9nXNnt00T16UPoSBvBKhNvVzQtj0=";
    };
    date = "2026-05-25";
  };
}
