return {
    "arduino_language_server",
    "astro",
    "autotools_ls",
    "awk_ls",
    "bashls",
    "bazelrc_lsp",
    -- 'biome',
    "buf_ls",
    "bzl",
    -- 'clangd',
    "cmake",
    "css_variables",
    -- 'cssls',
    "cssmodules_ls",
    -- 'denols',
    "docker_compose_language_service",
    "dockerls",
    -- 'eslint',
    "gdscript",
    "gopls",
    "gradle_ls",
    "graphql",
    "groovyls",
    "hls",
    "html",
    "java_language_server",
    -- 'jsonls',
    "kotlin_language_server",
    -- 'lua_ls',
    "marksman",
    "mesonlsp",
    "nginx_language_server",
    "nushell",
    "ocamllsp",
    "omnisharp",
    "phpactor",
    "pkgbuild_language_server",
    "powershell_es",
    "prismals",
    "pyright",
    "rnix",
    "ruff",
    "rust_analyzer",
    "stylelint_lsp",
    "taplo",
    "tailwindcss",
    "terraformls",
    -- 'tinymist',
    -- 'ts_ls',
    "vuels",
    -- 'yamlls',
    "zls",
}
